# Generated by Django 5.1.3 on 2024-11-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0024_remove_order_list_order_quantity_order_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
