# Generated by Django 5.1.3 on 2024-11-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0025_stuff_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
