# Generated by Django 5.1.3 on 2024-11-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0026_alter_stuff_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
