# Generated by Django 5.1.3 on 2024-11-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0028_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mall.stuff'),
        ),
    ]
